// Generates src/Vellum/web/js/icons.js from the lucide-static package (ISC license).
// usage: node tools/build-icons.mjs <path-to-node_modules/lucide-static>
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const lucide = process.argv[2];
const out = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../src/Vellum/web/js/icons.js');

const names = [
  'folder-open', 'file-plus', 'x', 'chevron-left', 'chevron-right', 'chevron-up', 'chevron-down',
  'zoom-in', 'zoom-out', 'rotate-cw', 'rotate-ccw', 'search', 'panel-left', 'layout-grid', 'list-tree',
  'file', 'gallery-vertical-end', 'printer', 'highlighter', 'underline', 'sticky-note', 'pen-line',
  'mouse-pointer-2', 'undo-2', 'redo-2', 'save', 'sun', 'moon', 'minus', 'square', 'copy', 'maximize-2',
  'minimize-2', 'lock', 'triangle-alert', 'file-x', 'clock', 'trash-2', 'move-horizontal', 'maximize',
  'case-sensitive', 'whole-word', 'external-link', 'ellipsis', 'check', 'plus', 'info', 'file-text',
  'book-open', 'text-select', 'key-round', 'eraser', 'save-all', 'arrow-up-to-line', 'arrow-down-to-line',
  'contrast', 'copy-plus', 'file-output', 'scissors', 'files', 'list-checks',
  'sparkles', 'refresh-cw', 'wifi-off',
];

const icons = {};
const missing = [];
for (const name of names) {
  const file = path.join(lucide, 'icons', `${name}.svg`);
  if (!fs.existsSync(file)) { missing.push(name); continue; }
  const svg = fs.readFileSync(file, 'utf8');
  const inner = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>'));
  icons[name] = inner.replace(/\s*\n\s*/g, '').trim();
}

const body = `// Generated by tools/build-icons.mjs from lucide-static (ISC license, https://lucide.dev). Do not edit.
const paths = ${JSON.stringify(icons, null, 1)};

/** Returns an inline SVG string for a monoline icon. */
export function icon(name, size = 18) {
  const inner = paths[name];
  if (!inner) throw new Error('Unknown icon ' + name);
  return \`<svg class="icon" width="\${size}" height="\${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${inner}</svg>\`;
}
`;
fs.writeFileSync(out, body);
console.log(`wrote ${Object.keys(icons).length} icons to ${out}`);
if (missing.length) console.log('MISSING:', missing.join(', '));
